# Dockerfile for wallet-portfolio
FROM golang:1.22-alpine

WORKDIR /app

# 1) Copy go.mod and go.sum first to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download

# 2) Copy the rest of the source code (including migrations folder)
COPY . .

# 3) Build your Go application (producing 'main' binary)
RUN go build -o main .

EXPOSE 8083

# 5) Set the default command to run your compiled binary
CMD ["./main"]