# ./order-history/Dockerfile
FROM golang:1.20-alpine AS builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod .

COPY go.sum .

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o order-history-service

# Final stage
FROM alpine:3.16

# Set working directory
WORKDIR /app

# Create migrations directory and copy migrations
RUN mkdir -p /app/migrations
COPY --from=builder /app/migrations /app/migrations

# Copy binary from builder
COPY --from=builder /app/order-history-service /app/

# Expose the service port
EXPOSE 8082

# Set entrypoint
ENTRYPOINT ["/app/order-history-service"]